/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.seodisparate.path_tree;

import org.junit.Test;
import static org.junit.Assert.*;

public class PathTreeTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }

    @Test public void test_print_list() {
        PathTree pathTree = new PathTree();

        System.out.println("Printing empty tree...");
        pathTree.printList();

        assertTrue(pathTree.put("/derp/doodle/doop"));

        System.out.println("Printing tree after put()...");
        pathTree.printList();

        assertTrue(pathTree.remove("/derp/doodle"));

        System.out.println("Printing tree after remove()...");
        pathTree.printList();
    }

    @Test public void test_put_remove() {
        PathTree pathTree = new PathTree();

        assertTrue(pathTree.put("/apple/banana/strawberry"));
        assertTrue(pathTree.put("/apple/milkshake/tart"));
        assertTrue(pathTree.put("/mango/blueberry/pizza"));

        assertFalse(pathTree.remove("apple/milkshake"));

        assertTrue(pathTree.remove("/apple"));
        assertTrue(pathTree.remove("/mango/blueberry"));

        pathTree.printList();
    }

    @Test public void test_partial_has() {
        PathTree pathTree = new PathTree();

        assertTrue(pathTree.put("/derp/a/doodle/doo"));

        assertTrue(pathTree.has("/"));
        assertTrue(pathTree.has("/derp"));
        assertTrue(pathTree.has("/derp/a"));
        assertTrue(pathTree.has("/derp/a/doodle"));
        assertTrue(pathTree.has("/derp/a/doodle/doo"));
    }
}
